### ISSUE TITLE
Specifying multiple colors does not generate multiple files

### ISSUE THREAD

**Issue by promethyttrium** [c1rrus/gulp-svg-fill#1] opened 2019-05-24 02:27 UTC
```
gulp.task('svg', function() {
  return gulp.src(['src/images/*.svg'])
    .pipe(svg_fill({
      colors: {
        black: '#000000',
        white: '#ffffff',
        red: '#ff0000'
      }
    }))
    .pipe(gulp.dest('./extension/images'));
});
```

A couple of `console.log`s told me that `currentFile.stem` is `undefined` so the rename is likely failing.

**Comment by c1rrus** [comment] 2019-05-30 22:18
Thanks for raising this. I'm not able to reproduce it though. What version of Gulp are you using?

**Comment by c1rrus** [comment] 2019-08-19 21:19
Closing this issue as I cannot reproduce it.

**Closed by c1rrus** 2019-08-19 21:19 UTC
